version: '3.7'
services:
  postgresql:
    image: postgres:12.0-alpine
    restart: always
    ports:
      - '8080:5432'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=postgresql
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
